-- migration_history
CREATE TABLE IF NOT EXISTS migration_history (
  version VARCHAR(255) NOT NULL PRIMARY KEY,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT
);

-- system_setting
CREATE TABLE IF NOT EXISTS system_setting (
  name VARCHAR(255) NOT NULL,
  value TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  UNIQUE(name)
);

-- user
CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  row_status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  username VARCHAR(255) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'USER',
  email VARCHAR(255) NOT NULL DEFAULT '',
  nickname VARCHAR(255) NOT NULL DEFAULT '',
  password_hash VARCHAR(255) NOT NULL,
  open_id VARCHAR(255) NOT NULL,
  avatar_url TEXT NOT NULL DEFAULT '',
  UNIQUE(username),
  UNIQUE(open_id)
);

-- user_setting
CREATE TABLE IF NOT EXISTS user_setting (
  user_id INT NOT NULL,
  key VARCHAR(255) NOT NULL,
  value TEXT NOT NULL,
  UNIQUE(user_id, key)
);

-- memo
CREATE TABLE IF NOT EXISTS memo (
  id SERIAL PRIMARY KEY,
  creator_id INT NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  row_status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  content TEXT NOT NULL DEFAULT '',
  visibility VARCHAR(32) NOT NULL DEFAULT 'PRIVATE'
);

-- memo_organizer
CREATE TABLE IF NOT EXISTS memo_organizer (
  id SERIAL PRIMARY KEY,
  memo_id INT NOT NULL,
  user_id INT NOT NULL,
  pinned BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(memo_id, user_id)
);

-- shortcut
CREATE TABLE IF NOT EXISTS shortcut (
  id SERIAL PRIMARY KEY,
  creator_id INT NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  row_status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  title VARCHAR(255) NOT NULL DEFAULT '',
  payload TEXT NOT NULL DEFAULT '{}'
);

-- resource
CREATE TABLE IF NOT EXISTS resource (
  id SERIAL PRIMARY KEY,
  creator_id INT NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  filename VARCHAR(255) NOT NULL DEFAULT '',
  blob BYTEA DEFAULT NULL,
  external_link TEXT NOT NULL DEFAULT '',
  type VARCHAR(255) NOT NULL DEFAULT '',
  size BIGINT NOT NULL DEFAULT 0,
  internal_path TEXT NOT NULL DEFAULT ''
);

-- memo_resource
CREATE TABLE IF NOT EXISTS memo_resource (
  memo_id INT NOT NULL,
  resource_id INT NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  updated_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  UNIQUE(memo_id, resource_id)
);

-- memo_relation
CREATE TABLE IF NOT EXISTS memo_relation (
  memo_id INT NOT NULL,
  related_memo_id INT NOT NULL,
  type VARCHAR(64) NOT NULL,
  UNIQUE(memo_id, related_memo_id, type)
);

-- tag
CREATE TABLE IF NOT EXISTS tag (
  name VARCHAR(255) NOT NULL,
  creator_id INT NOT NULL,
  UNIQUE(name, creator_id)
);

-- activity
CREATE TABLE IF NOT EXISTS activity (
  id SERIAL PRIMARY KEY,
  creator_id INT NOT NULL,
  created_ts BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM NOW())::BIGINT,
  type VARCHAR(255) NOT NULL DEFAULT '',
  level VARCHAR(32) NOT NULL DEFAULT 'INFO',
  payload TEXT NOT NULL DEFAULT '{}'
);

-- storage
CREATE TABLE IF NOT EXISTS storage (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  config TEXT NOT NULL DEFAULT '{}'
);

-- idp
CREATE TABLE IF NOT EXISTS idp (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  identifier_filter VARCHAR(255) NOT NULL DEFAULT '',
  config TEXT NOT NULL DEFAULT '{}'
);
